import type { Metadata } from "next";
import "./globals.css";
import {dynapuff} from "@/lib/fonts";

const title = "Lorcle";

export const metadata: Metadata = {
  title: title,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <meta name="google-site-verification" content="BmDIQRiicmINpQRCfdH0FOJm701KgFaGcUnXLSSw0EA" />
          <title>{title}</title>
      </head>
      <body className={dynapuff.className}>
        {children}
      </body>
    </html>
  );
}
