import type { Metadata } from "next";
import "./globals.css";
import {dynapuff} from "@/app/lib/fonts";

export const metadata: Metadata = {
  title: "Lorcle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dynapuff.className}>
        {children}
      </body>
    </html>
  );
}
